# Â© Andrew Wei

version: 2
jobs:
  build_and_test:
    working_directory: ~/repo
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run:
          name: Install APT packages
          command: apt-get update -y && apt-get install jq -y
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
      - run:
          name: Pack
          command: .circleci/pack.sh
      - store_artifacts:
          path: ~/repo/package

  build_test_and_deploy:
    working_directory: ~/repo
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run:
          name: Install APT packages
          command: apt-get update -y && apt-get install jq -y
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
      - run:
          name: Pack
          command: .circleci/pack.sh
      - store_artifacts:
          path: ~/repo/package
      - deploy:
          name: Deploy to NPM
          command: .circleci/deploy_to_npm.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            tags:
              ignore: /^v.*/
  build_test_and_deploy:
    jobs:
      - build_test_and_deploy:
          context: npm_deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
